"""
API Schemas Package
"""
from .profile_schemas import (
    ProfileCreate,
    ProfileUpdate,
    ProfileRead,
    UserSettingsUpdate,
    UserSettingsRead,
    UserStatsRead,
    UserProfileRead,
    UserProfileUpdate,
    UserAccountTypeUpdate,
    PublicProfileRead,
    LocationCreate,
    LocationRead,
    LanguageCreate,
    LanguageRead,
    SocialLinksCreate,
    SocialLinksRead,
)

from .crew_profile_schemas import (
    SkillCreate,
    SkillRead,
    ExperienceCreate,
    ExperienceUpdate,
    ExperienceRead,
    EducationCreate,
    EducationUpdate,
    EducationRead,
    CertificationCreate,
    CertificationUpdate,
    CertificationRead,
    AvailabilityCreate,
    AvailabilityRead,
    ProductionPreferencesCreate,
    ProductionPreferencesRead,
    RatingRead,
    CrewProfileCreate,
    CrewProfileUpdate,
    CrewProfileRead,
    PublicCrewProfileRead,
)

__all__ = [
    # Profile schemas
    "ProfileCreate",
    "ProfileUpdate",
    "ProfileRead",
    "UserSettingsUpdate",
    "UserSettingsRead",
    "UserStatsRead",
    "UserProfileRead",
    "UserProfileUpdate",
    "UserAccountTypeUpdate",
    "PublicProfileRead",
    "LocationCreate",
    "LocationRead",
    "LanguageCreate",
    "LanguageRead",
    "SocialLinksCreate",
    "SocialLinksRead",
    # Crew profile schemas
    "SkillCreate",
    "SkillRead",
    "ExperienceCreate",
    "ExperienceUpdate",
    "ExperienceRead",
    "EducationCreate",
    "EducationUpdate",
    "EducationRead",
    "CertificationCreate",
    "CertificationUpdate",
    "CertificationRead",
    "AvailabilityCreate",
    "AvailabilityRead",
    "ProductionPreferencesCreate",
    "ProductionPreferencesRead",
    "RatingRead",
    "CrewProfileCreate",
    "CrewProfileUpdate",
    "CrewProfileRead",
    "PublicCrewProfileRead",
]
